import { ArrowCounterClockwise, ArrowRight, Check, ClockCountdown, Flag, MapPin, Package, Path, Pause, Sparkle, Truck, Warning, X } from '@phosphor-icons/react'
import { useEffect, useMemo, useState } from 'react'
import { CampusMap, RouteSequence } from '../components/CampusMap'
import { ActionFeedback, Button, EmptyState, SectionHeading, Skeleton, StatusBadge } from '../components/Ui'
import { stopsForRoute } from '../lib/mapGeometry'
import { useApp } from '../state/AppContext'
import type { Building, Order, Trip } from '../types'

function useRemaining(target: number | null) {
  const [now, setNow] = useState(Date.now())
  useEffect(() => { if (!target) return; const timer = window.setInterval(() => setNow(Date.now()), 250); return () => window.clearInterval(timer) }, [target])
  return target ? Math.max(0, Math.ceil((target - now) / 1000)) : 0
}

export function ShipperDashboard() {
  const app = useApp()
  const { data, actions, arrivedAt, countdownEndsAt, announcedStops, createTrip, confirmRoute, rejectRoute, cancelCountdown, announceStop, arriveStop, setOutcome, completeStop, markUnavailable, recalculate } = app
  const [comparison, setComparison] = useState(false)
  const trip = data.trip
  const readyCount = data.orders.filter((order) => order.status === 'READY').length
  const currentStop = trip?.stops.find((stop) => stop.id === trip.currentStopId)
  const currentBuilding = data.buildings.find((building) => building.id === currentStop?.buildingId)
  const currentOrders = data.orders.filter((order) => currentStop?.orderIds.includes(order.id))
  const countdown = useRemaining(countdownEndsAt ?? (trip?.countdownEndsAt ? Date.parse(trip.countdownEndsAt) : null))
  const arrivedTarget = currentStop?.minimumWaitEndsAt ? Date.parse(currentStop.minimumWaitEndsAt) : currentStop && arrivedAt[currentStop.id] ? arrivedAt[currentStop.id] + 120000 : null
  const waitRemaining = useRemaining(arrivedTarget)
  const outcomeComplete = currentOrders.length > 0 && currentOrders.every((order) => ['DELIVERED', 'TEMP_WAITING', 'FAILED_DELIVERY'].includes(order.status))
  const isNextStop = Boolean(currentStop && ['NEXT', 'RETRY_NEXT'].includes(currentStop.status))
  const isArrivedStop = Boolean(currentStop && ['ARRIVED', 'RETRY_ARRIVED'].includes(currentStop.status))

  if (actions['create-trip'] === 'loading') return <GenerationLoading />
  if (!trip) return <ReadyState merchantName={data.merchants.find((merchant) => merchant.id === app.session?.merchantId)?.name} readyCount={readyCount} busy={false} error={actions['create-trip'] === 'error'} onReady={createTrip} />
  if (trip.status === 'AWAITING_SHIPPER_CONFIRMATION') return <RouteReview onConfirm={confirmRoute} onReject={rejectRoute} />
  if (trip.status === 'STARTING') return <Countdown seconds={countdown} onCancel={cancelCountdown} busy={actions['cancel-countdown'] === 'loading'} />
  if (trip.status === 'COMPLETED') return <Completion />

  return <div className="space-y-12">
    <header className="grid gap-6 md:grid-cols-[minmax(0,1fr)_auto] md:items-end"><div className="min-w-0"><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.18em] text-emerald-800"><Truck size={14} />Active shipper route</div><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">{currentBuilding ? `${currentBuilding.name} is ${isArrivedStop ? 'in service' : 'up next'}.` : 'Continue the route.'}</h1></div><div className="flex min-w-0 items-center gap-3"><StatusBadge status={trip.status} /><span className="max-w-48 truncate font-mono text-xs text-zinc-500" title={trip.id}>{trip.id}</span></div></header>

    <section className="space-y-5"><CampusMap buildings={data.buildings} trip={trip} wide /><div className="grid gap-5 border-y border-zinc-300 py-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div><div className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-[.15em] text-emerald-800"><MapPin size={15} />Current stop</div><h2 className="mt-2 text-2xl font-semibold tracking-tight">{currentBuilding?.name ?? 'Route origin'}</h2><p className="mt-1 text-sm text-zinc-500">{currentBuilding?.pickupLabel}</p>{isNextStop && currentStop && !currentStop.announcedAt && !announcedStops.includes(currentStop.id) && <p className="mt-2 text-xs text-zinc-500">Students can see your position now. Their route opens after you announce this building.</p>}</div><div className="flex flex-wrap items-center gap-2">{isNextStop && currentStop && <>{currentStop.announcedAt || announcedStops.includes(currentStop.id) ? <span className="rounded-lg bg-emerald-50 px-3 py-2 text-xs font-medium text-emerald-800">Students are tracking live</span> : <Button tone="secondary" busy={actions[`announce-${currentStop.id}`] === 'loading'} onClick={() => void announceStop(currentStop.id)}><Flag size={16} />Heading to this building</Button>}<Button disabled={!currentStop.announcedAt && !announcedStops.includes(currentStop.id)} busy={actions[`arrive-${currentStop.id}`] === 'loading'} onClick={() => void arriveStop(currentStop.id)}>Mark arrived <ArrowRight size={16} /></Button></>}{isArrivedStop && <div><p className="font-mono text-3xl font-semibold tabular-nums">{String(Math.floor(waitRemaining / 60)).padStart(2, '0')}:{String(waitRemaining % 60).padStart(2, '0')}</p><p className="mt-1 text-xs text-zinc-500">{waitRemaining > 0 ? 'until unavailable actions unlock' : 'unavailable actions are unlocked'}</p></div>}</div></div></section>

    {isArrivedStop && currentStop && <section><SectionHeading eyebrow="Individual outcomes" title={`${currentOrders.length} orders at ${currentBuilding?.name ?? 'this building'}`} aside={<span className="font-mono text-xs text-zinc-500">Delivered is always available</span>} /><div className="divide-y divide-zinc-200 border-y border-zinc-200">{currentOrders.map((order) => <OrderOutcome key={order.id} order={order} stopId={currentStop.id} waitRemaining={waitRemaining} busy={actions[`outcome-${order.id}`] === 'loading'} setOutcome={setOutcome} />)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-4"><p className="max-w-lg text-xs leading-relaxed text-zinc-500">Complete the stop only after every order is delivered or manually moved to temporary waiting.</p><Button disabled={!outcomeComplete} busy={actions[`complete-${currentStop.id}`] === 'loading'} onClick={() => void completeStop(currentStop.id)}>Complete stop <Check size={17} /></Button></div></section>}

    <section><SectionHeading eyebrow="Recommended Route" title="Remaining building sequence" /><RouteSequence stops={trip.stops} buildings={data.buildings} currentStopId={trip.currentStopId} /><div className="mt-6 flex flex-wrap gap-2"><Button tone="secondary" busy={actions.recalculate === 'loading'} onClick={() => { void recalculate().then((ready) => ready && setComparison(true)) }}><Path size={17} />Recalculate remaining route</Button>{trip.stops.filter((stop) => ['WAITING', 'NEXT'].includes(stop.status) && stop.id !== trip.currentStopId).slice(0, 1).map((stop) => <Button key={stop.id} tone="quiet" busy={actions[`unavailable-${stop.id}`] === 'loading'} onClick={() => void markUnavailable(stop.id)}><Warning size={17} />{data.buildings.find((building) => building.id === stop.buildingId)?.name ?? 'Building'} unavailable</Button>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-zinc-200 pt-4 text-xs text-zinc-500"><span><strong className="font-medium text-zinc-800">Demo GPS automatic</strong> · campus gate captured · publishes every 1 second</span><span className="font-mono uppercase tracking-[.12em] text-emerald-800">{trip.gps.playbackStatus === 'WAITING_AT_STOP' ? 'Waiting at stop' : trip.gps.playbackStatus === 'PLAYING' ? 'Moving' : trip.gps.playbackStatus?.replaceAll('_', ' ') ?? 'Active'}</span></div></section>

    {comparison && <RouteComparison trip={trip} buildings={data.buildings} onKeep={() => setComparison(false)} onConfirm={() => { setComparison(false); void confirmRoute() }} />}
  </div>
}

function ReadyState({ merchantName, readyCount, busy, error, onReady }: { merchantName?: string; readyCount: number; busy: boolean; error: boolean; onReady: () => Promise<void> }) {
  return <div className="grid min-h-[calc(100dvh-12rem)] items-center gap-10 py-6 md:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)]"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-emerald-800">Approved shipper · {merchantName ?? 'Active merchant'}</p><h1 className="mt-4 max-w-2xl text-4xl font-semibold leading-[.98] tracking-[-.045em] md:text-6xl">Build today’s route when you arrive.</h1><p className="mt-6 max-w-[58ch] text-base leading-relaxed text-zinc-600">Pressing Ready sends the demo position at the campus gate, locks every eligible order, and builds the route from that exact point.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Button className="min-h-13 px-6" busy={busy} disabled={readyCount === 0} onClick={() => void onReady()}><Truck size={19} />Ready to deliver</Button><span className="font-mono text-xs text-zinc-500">{readyCount} eligible order{readyCount === 1 ? '' : 's'}</span></div>{readyCount === 0 && <p className="mt-3 text-sm text-zinc-500">No ready orders are available for this merchant yet.</p>}<ActionFeedback state={error ? 'error' : undefined} /></div><div className="relative overflow-hidden rounded-[2.5rem] border border-zinc-200 bg-white p-8 shadow-[0_24px_55px_-35px_rgba(24,24,27,.3)]"><div className="absolute right-0 top-0 h-32 w-32 translate-x-1/3 -translate-y-1/3 rounded-full bg-emerald-100" /><Sparkle size={23} className="relative text-emerald-700" /><p className="relative mt-16 font-mono text-[10px] uppercase tracking-[.16em] text-zinc-500">Generation pipeline</p><ol className="relative mt-4 divide-y divide-zinc-200">{['Capture campus-gate coordinate', 'Lock eligible orders', 'AI analyzes priorities', 'OR-Tools calculates route'].map((item, index) => <li key={item} className="flex items-center gap-4 py-4"><span className="font-mono text-xs text-emerald-800">0{index + 1}</span><span className="text-sm font-medium">{item}</span></li>)}</ol></div></div>
}

function GenerationLoading() {
  return <div className="mx-auto max-w-4xl py-16"><div className="mb-10"><p className="font-mono text-[10px] uppercase tracking-[.18em] text-emerald-800">Trip generation</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Building a controlled snapshot.</h1><p className="mt-4 text-sm text-zinc-500">Orders are locked while analysis and solver validation run.</p></div><Skeleton rows={4} /></div>
}

function RouteReview({ onConfirm, onReject }: { onConfirm: () => Promise<void>; onReject: () => Promise<void> }) {
  const { data, actions } = useApp(); const trip = data.trip!
  const proposedStops = stopsForRoute(trip, 'proposed')
  return <div className="space-y-8"><header className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-emerald-800">Human confirmation required</p><h1 className="mt-3 text-3xl font-semibold tracking-[-.04em] md:text-5xl">Review the Recommended Route.</h1></div><StatusBadge status={trip.status} /></header><CampusMap buildings={data.buildings} trip={trip} routeMode="proposed" wide /><div className="border-y border-zinc-300 py-5"><SectionHeading eyebrow={`${trip.stops.reduce((sum, stop) => sum + stop.orderIds.length, 0)} included orders`} title={`${trip.stops.length} building stops`} aside={<span className="font-mono text-xs">~{trip.estimatedMinutes} min</span>} /><RouteSequence stops={proposedStops} buildings={data.buildings} /><div className="mt-5 border-t border-zinc-200 pt-5"><p className="text-xs font-semibold">Why this sequence</p><ul className="mt-3 space-y-2 text-sm leading-relaxed text-zinc-500">{trip.routeExplanation.map((item) => <li key={item}>— {item}</li>)}</ul></div></div><div className="sticky bottom-4 flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-white/80 bg-white/90 p-4 shadow-[0_18px_45px_-28px_rgba(24,24,27,.45)] backdrop-blur-xl"><p className="text-xs text-zinc-500">Confirmation begins a cancellable five-second countdown.</p><div className="flex gap-2"><Button tone="secondary" busy={actions['reject-route'] === 'loading'} onClick={() => void onReject()}><X size={16} />Reject</Button><Button busy={actions['confirm-route'] === 'loading'} onClick={() => void onConfirm()}>Confirm route <Check size={16} /></Button></div></div></div>
}

function Countdown({ seconds, onCancel, busy }: { seconds: number; onCancel: () => Promise<void>; busy: boolean }) {
  return <div className="grid min-h-[calc(100dvh-12rem)] place-items-center"><div className="w-full max-w-2xl rounded-[2.5rem] bg-zinc-900 px-6 py-14 text-center text-white md:px-12"><ClockCountdown size={30} className="mx-auto text-emerald-400" /><p className="mt-8 font-mono text-[10px] uppercase tracking-[.2em] text-zinc-400">Route activates in</p><p className="mt-3 font-mono text-[clamp(5rem,22vw,10rem)] font-semibold leading-none tabular-nums">{seconds}</p><p className="mx-auto mt-5 max-w-md text-sm leading-relaxed text-zinc-400">Students receive the trip-start notice when the countdown completes.</p><Button className="mt-8 bg-white text-zinc-900 hover:bg-zinc-100" busy={busy} onClick={() => void onCancel()}><Pause size={17} />Cancel countdown</Button></div></div>
}

function OrderOutcome({ order, stopId, waitRemaining, busy, setOutcome }: { order: Order; stopId: string; waitRemaining: number; busy: boolean; setOutcome: (stopId: string, orderId: string, outcome: 'DELIVERED' | 'TEMP_WAITING' | 'FAILED_DELIVERY') => Promise<void> }) {
  const terminal = ['DELIVERED', 'FAILED_DELIVERY'].includes(order.status)
  const studentLabel = order.studentName.startsWith('user_') ? 'Student pickup' : order.studentName
  const buildingCode = order.buildingId.replace(/^building_/i, '').toUpperCase()
  const orderCode = order.id.replace(/^order_/i, '').toUpperCase()
  return <div className="grid gap-4 py-5 md:grid-cols-[1fr_auto] md:items-center"><div className="flex items-start gap-4"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-zinc-100 font-mono text-[10px] text-zinc-600">{buildingCode}</span><div><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold">{studentLabel}</p><StatusBadge status={order.status} /></div><p className="mt-1 text-xs text-zinc-500">Order {orderCode} · {order.productName}</p></div></div>{!terminal && <div className="flex flex-wrap gap-2 md:justify-end"><Button busy={busy} onClick={() => void setOutcome(stopId, order.id, 'DELIVERED')}><Check size={16} />Delivered</Button><Button tone="secondary" busy={busy} disabled={waitRemaining > 0} onClick={() => void setOutcome(stopId, order.id, order.attempt === 2 ? 'FAILED_DELIVERY' : 'TEMP_WAITING')}>{order.attempt === 2 ? 'Failed delivery' : 'Customer unavailable'} {waitRemaining > 0 && <span className="font-mono text-[10px]">{waitRemaining}s</span>}</Button></div>}</div>
}

function RouteComparison({ trip, buildings, onKeep, onConfirm }: { trip: Trip; buildings: Building[]; onKeep: () => void; onConfirm: () => void }) {
  const label = (stopId: string) => buildings.find((building) => building.id === trip.stops.find((stop) => stop.id === stopId)?.buildingId)?.name.split(' ')[0] ?? stopId
  const current = (trip.currentRoute ?? trip.stops.map((stop) => stop.id)).map(label).join(' → ')
  const proposed = (trip.proposedRoute ?? trip.stops.map((stop) => stop.id)).map(label).join(' → ')
  return <div className="fixed inset-0 z-40 grid place-items-end bg-zinc-950/35 p-0 backdrop-blur-sm md:place-items-center md:p-6" role="dialog" aria-modal="true" aria-labelledby="route-comparison-title"><div className="max-h-[90dvh] w-full max-w-2xl overflow-auto rounded-t-[2rem] bg-white p-6 shadow-2xl md:rounded-[2rem] md:p-8"><p className="font-mono text-[10px] uppercase tracking-[.16em] text-emerald-800">Fresh snapshot</p><h2 id="route-comparison-title" className="mt-2 text-2xl font-semibold tracking-tight">Compare remaining routes</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><div className="rounded-2xl bg-zinc-100 p-5"><p className="text-xs text-zinc-500">Current route</p><p className="mt-3 font-mono text-lg font-semibold">{current}</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-xs text-emerald-800">Recommended route</p><p className="mt-3 font-mono text-lg font-semibold text-emerald-950">{proposed}</p></div></div><div className="mt-6 border-y border-zinc-200 py-5"><p className="text-sm font-semibold">Estimated impact</p><ul className="mt-3 space-y-2 text-sm text-zinc-600">{trip.routeExplanation.map((reason) => <li key={reason}>{reason}</li>)}</ul></div><p className="mt-5 text-xs text-zinc-500">Current and completed stops remain immutable.</p><div className="mt-6 flex justify-end gap-2"><Button tone="secondary" onClick={onKeep}>Keep current route</Button><Button onClick={onConfirm}>Confirm new route</Button></div></div></div>
}

function Completion() {
  const { data, resetDemo, actions } = useApp(); const delivered = data.orders.filter((order) => order.status === 'DELIVERED').length; const failed = data.orders.filter((order) => order.status === 'FAILED_DELIVERY').length
  return <div className="mx-auto max-w-4xl py-10"><div className="rounded-[2.5rem] bg-zinc-900 p-8 text-white md:p-12"><Check size={29} className="text-emerald-400" /><p className="mt-16 font-mono text-[10px] uppercase tracking-[.18em] text-zinc-400">Trip completed</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em]">Every order has an outcome.</h1><div className="mt-10 grid grid-cols-2 gap-4 border-t border-zinc-700 pt-7"><div><p className="font-mono text-3xl">{delivered}</p><p className="mt-1 text-xs text-zinc-400">delivered</p></div><div><p className="font-mono text-3xl">{failed}</p><p className="mt-1 text-xs text-zinc-400">failed after retry</p></div></div><Button className="mt-9 bg-white text-zinc-900 hover:bg-zinc-100" busy={actions.reset === 'loading'} onClick={() => void resetDemo()}><ArrowCounterClockwise size={17} />Restore demo</Button></div></div>
}
